// Makes the puzzle pieces draggable
$(function()
        {
         $("#MoveMe1").draggable();
         $("#MoveMe2").draggable();
         $("#MoveMe3").draggable();
         $("#MoveMe4").draggable();
         $("#MoveMe5").draggable();
         $("#MoveMe6").draggable();
         $("#MoveMe7").draggable();
         $("#MoveMe8").draggable();
         $("#MoveMe9").draggable();
         $("#MoveMe10").draggable();
         $("#MoveMe11").draggable();
         $("#MoveMe12").draggable();
         $("#MoveMe13").draggable();
         $("#MoveMe14").draggable();
         $("#MoveMe15").draggable();
         $("#MoveMe16").draggable();
         $("#MoveMe17").draggable();
         $("#MoveMe18").draggable();
         $("#MoveMe19").draggable();
         $("#MoveMe20").draggable();
         $("#MoveMe21").draggable();
         $("#MoveMe22").draggable();
         $("#MoveMe23").draggable();
         $("#MoveMe24").draggable();
         $("#MoveMe25").draggable();
        });